version: '4'

services:
  db:
    container_name: mmd_postgres
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file:
      - ./.env.db
  pgadmin:
    container_name: mmd_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-mmd.stock@uca.kg}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-developer}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5055}:80"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge

volumes:
  postgres_data:
  pgadmin:
